version: "2"

services:
  ethereum.node1.com:
    image: "pjt3591oo/ethereum-geth:1.90"
    tty: true
    ports:
      - 8545:8545
      - 30305:30305
    environment:
      ENV: ETHERNODE1
      RPCPORT: 8545
      PORT: 30303
    volumes:
      - ./genesis2.json:/ethereum/genesis.json
    container_name: ethereum.node1.com
    command: >
      sh -c "geth --datadir $PWD init genesis.json
            geth --networkid 1234 --datadir /ethereum --rpc --rpcport 8545 --rpcaddr '0.0.0.0' --rpcvhosts='*' --rpccorsdomain '*' --rpcapi 'admin,db,eth,debug,miner,net,shh,txpool,web3' --port 30303"
    working_dir: /ethereum

  ethereum.node2.com:
    image: "pjt3591oo/ethereum-geth:1.90"
    tty: true
    ports:
      - 8546:8546
      - 30304:30304
    environment:
      ENV: ETHERNODE2
      RPCPORT: 8546
      PORT: 30304
    volumes:
      - ./genesis2.json:/ethereum/genesis.json
    container_name: ethereum.node2.com
    command: >
      sh -c "geth --datadir $PWD init genesis.json
            geth --networkid 1234 --datadir /ethereum --rpc --rpcport 8545 --rpcaddr '0.0.0.0' --rpcvhosts='*' --rpccorsdomain '*' --rpcapi 'admin,db,eth,debug,miner,net,shh,txpool,web3' --port 30303"
    working_dir: /ethereum

  cli:
    image: "pjt3591oo/ethereum-geth:1.90"
    tty: true
    container_name: cli
    working_dir: /ethereum
    command: /bin/bash
    depends_on:
      - ethereum.node1.com
      - ethereum.node2.com
